CREATE TABLE PRICES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   INT            NOT NULL,
    PRODUCT_ID INT            NOT NULL,
    PRICE_LIST INT            NOT NULL,
    PRIORITY   INT            NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURR       VARCHAR(3)     NOT NULL
);

CREATE INDEX IDX_PRICES_LOOKUP
    ON PRICES (PRODUCT_ID, BRAND_ID, START_DATE, END_DATE, PRIORITY);

CREATE INDEX IDX_PRICES_DATES
    ON PRICES (START_DATE, END_DATE);

ALTER TABLE PRICES
    ADD CONSTRAINT CHK_PRICE_POSITIVE CHECK (PRICE >= 0);

ALTER TABLE PRICES
    ADD CONSTRAINT CHK_DATE_RANGE CHECK (END_DATE >= START_DATE);